import * as vscode from 'vscode';
import OpenAI from "openai";
import { FunctionInfo } from '../types';
import { AnnotationContent } from '../types';

export async function createChatCompletion(messages: OpenAI.Chat.ChatCompletionMessageParam[]) {
  
  const config = vscode.workspace.getConfiguration('functionAnnotations');
  const apiKey = config.get<string>('openaiApiKey');
  if (!apiKey) {
      throw new Error('OpenAI API Key is not set in the extension settings.');
  }
  const client = new OpenAI({
      apiKey: apiKey
  }); 
  const completion = await client.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: messages,
    }); 
    
    return completion;
}

export async function generateAnnotation(
  functionInfo: FunctionInfo
): Promise<AnnotationContent> {
  const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
    {
      role: "system",
      content: "You are a helpful assistant that generates concise summaries and visualizations for code functions."
    },
    {
      role: "user",
      content: `Generate a concise summary and visualization for the following function: 
      ${functionInfo.name}. Here is the full function: ${functionInfo.functionCode}. 
      What variables, information, or function walkthroughs would be most helpful to understand this function behavior quickly?`
    }
    ];
  const completion = await createChatCompletion(messages);
  const llmResponse = completion.choices[0].message.content;
  if (!llmResponse) {
    throw new Error('No response generated by the LLM.');
  }
  const content: AnnotationContent = {
    functionName: functionInfo.name,
    summary: llmResponse, 
    timestamp: new Date(),
    isLoading: false
  };
  
  return content;
}