import * as path from 'path';
import { readFile } from 'fs/promises';
import * as vscode from 'vscode';
import OpenAI from "openai";
import { FunctionInfo } from '../types';
import { AnnotationContent } from '../types';

// Cache the developer prompt to avoid reading file on every call
let cachedDevPrompt: string | null = null;

async function loadDevPrompt(extensionPath: string): Promise<string> {
  if (!cachedDevPrompt) {
    const promptPath = path.join(extensionPath, 'src', 'services', 'dev_prompt.txt');
    cachedDevPrompt = await readFile(promptPath, 'utf-8');
  }
  return cachedDevPrompt;
}

async function convertMarkdownToHtml(markdown: string): Promise<string> {
  try {
    const { marked } = await import('marked');
    const html = marked.parse(markdown);
    return typeof html === 'string' ? html : markdown;
  } catch (error) {
    return markdown; // Fallback to original if conversion fails
  }
}

export async function createChatCompletion(messages: OpenAI.Chat.ChatCompletionMessageParam[]) {
  
  const config = vscode.workspace.getConfiguration('functionAnnotations');
  const apiKey = config.get<string>('openaiApiKey');
  if (!apiKey) {
      throw new Error('OpenAI API Key is not set in the extension settings.');
  }
  const client = new OpenAI({
      apiKey: apiKey
  }); 
  const completion = await client.chat.completions.create({
        model: "gpt-4.1",
        messages: messages,
    }); 
    
    return completion;
}

export async function generateAnnotation(
  functionInfo: FunctionInfo,
  context: vscode.ExtensionContext
): Promise<AnnotationContent> {
  const dev_prompt = await loadDevPrompt(context.extensionPath);
  const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
    {
      role: "developer",
      content: dev_prompt
    },
    {
      role: "user",
      content: `Analyze the following function by providing relevant information that would 
      help a developer understand it quickly:
      Function Name: ${functionInfo.name}
      Code:
      \`\`\`
      ${functionInfo.functionCode}
      \`\`\`
      Focus on: parameters, return value, key logic steps, dependencies, and anything else 
      deemed important for understanding the function's purpose and behavior.`
    }
  ];
  
  const completion = await createChatCompletion(messages);
  const llmResponse = completion.choices[0].message.content;
  if (!llmResponse) {
    throw new Error('No response generated by the LLM.');
  }
  const content: AnnotationContent = {
    functionName: functionInfo.name,
    summary: await convertMarkdownToHtml(llmResponse), 
    timestamp: new Date(),
    isLoading: false
  };
  
  return content;
}