/**
 * mockLLMService.ts
 * 
 * Provides mock/fake LLM responses for development and testing.
 * 
 * This service simulates what a real LLM would return, including:
 * - Realistic response delay (500ms)
 * - Function analysis
 * - HTML visualizations
 * - Metadata
 * 
 * In production, this will be replaced with a real LLM service
 * that calls OpenAI, Anthropic, or other APIs.
 * 
 * Benefits of mock data:
 * - No API keys required
 * - Instant testing
 * - No API costs
 * - Predictable output
 */
import * as vscode from 'vscode';
import { FunctionInfo, AnnotationContent } from '../types';
/**
 * Generates a mock annotation for a given function.
 * 
 * Simulates an LLM API call by:
 * 1. Waiting 500ms (simulates network delay)
 * 2. Generating fake but realistic analysis
 * 3. Creating HTML visualization
 * 4. Returning AnnotationContent
 * 
 * @param functionInfo - Information about the function to analyze
 * @returns Promise that resolves to annotation content
 * 
 * Example usage:
 *   const content = await generateAnnotation(functionInfo, context);
 *   console.log(content.summary); // "This function calculates..."
 */
export async function generateAnnotation(
  functionInfo: FunctionInfo
): Promise<AnnotationContent> {
  
  // Simulate network delay (like calling a real API)
  await sleep(500);
  
  // Generate mock content
  const content: AnnotationContent = {
    functionName: functionInfo.name,
    summary: generateMockSummary(functionInfo),
    timestamp: new Date(),
    isLoading: false
  };
  
  return content;
}
/**
 * Sleeps for a specified number of milliseconds.
 * Used to simulate API call delay.
 * 
 * @param ms - Number of milliseconds to sleep
 * @returns Promise that resolves after the delay
 * 
 * Example:
 *   await sleep(1000); // Waits 1 second
 */
function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
/**
 * Generates a mock summary based on function information.
 * 
 * In a real implementation, this would be generated by an LLM.
 * For now, we create a simple template-based summary.
 * 
 * @param functionInfo - The function to summarize
 * @returns Mock summary text
 */
function generateMockSummary(functionInfo: FunctionInfo): string {
  const symbolType = getSymbolKindName(functionInfo.symbolKind);
  const lineCount = functionInfo.endLine - functionInfo.startLine + 1;
  
  return `This is a mock analysis of the ${symbolType.toLowerCase()} "${functionInfo.name}". ` +
         `It spans ${lineCount} lines of code. ` +
         `In a production environment, this would contain an AI-generated summary ` +
         `explaining the function's purpose, parameters, return value, and potential improvements.`;
}
/**
 * Generates mock HTML visualization for the function.
 * 
 * Creates a structured HTML display with:
 * - Function metadata
 * - Mock analysis metrics
 * - Code preview
 * 
 * In production, this would be LLM-generated and much richer
 * (charts, diagrams, interactive elements, etc.)
 * 
 * @param functionInfo - The function to visualize
 * @returns HTML string
 */
function generateMockVisualization(functionInfo: FunctionInfo): string {
  const symbolType = getSymbolKindName(functionInfo.symbolKind);
  const lineCount = functionInfo.endLine - functionInfo.startLine + 1;
  const codePreview = getCodePreview(functionInfo.functionCode);
  
  return `
    <div class="mock-visualization">
      <h3>📊 Function Analysis (Mock Data)</h3>
      
      <div class="metadata">
        <p><strong>Name:</strong> <code>${functionInfo.name}</code></p>
        <p><strong>Type:</strong> ${symbolType}</p>
        <p><strong>Lines:</strong> ${functionInfo.startLine + 1} - ${functionInfo.endLine + 1}</p>
        <p><strong>Total Lines:</strong> ${lineCount}</p>
      </div>
      
      <h4>🎯 Mock Insights</h4>
      <ul class="insights">
        <li>📈 Estimated Complexity: ${getMockComplexity(lineCount)}</li>
        <li>⚡ Performance: ${getMockPerformance()}</li>
        <li>🔍 Readability: ${getMockReadability()}</li>
        <li>🧪 Test Coverage: ${getMockTestCoverage()}</li>
      </ul>
      
      <h4>📝 Code Preview</h4>
      <pre class="code-preview"><code>${escapeHtml(codePreview)}</code></pre>
      
      <div class="disclaimer">
        <em>⚠️ This is mock data for development. Real LLM integration coming soon!</em>
      </div>
    </div>
  `;
}
/**
 * Converts a SymbolKind enum to a human-readable string.
 * 
 * @param kind - The symbol kind enum
 * @returns Readable name
 */
function getSymbolKindName(kind: vscode.SymbolKind): string {
  switch (kind) {
    case vscode.SymbolKind.Function:
      return 'Function';
    case vscode.SymbolKind.Method:
      return 'Method';
    case vscode.SymbolKind.Constructor:
      return 'Constructor';
    default:
      return 'Unknown';
  }
}
/**
 * Gets a preview of the function code (first 10 lines).
 * Prevents huge code blocks from cluttering the visualization.
 * 
 * @param code - The full function code
 * @returns Truncated code preview
 */
function getCodePreview(code: string): string {
  const lines = code.split('\n');
  const maxLines = 10;
  
  if (lines.length <= maxLines) {
    return code;
  }
  
  const preview = lines.slice(0, maxLines).join('\n');
  return preview + '\n... (truncated)';
}
/**
 * Escapes HTML special characters to prevent rendering issues.
 * Essential for displaying code that contains <, >, &, etc.
 * 
 * @param text - Text to escape
 * @returns HTML-safe text
 */
function escapeHtml(text: string): string {
  const htmlEscapes: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;'
  };
  
  return text.replace(/[&<>"']/g, (char) => htmlEscapes[char]);
}
/**
 * Generates mock complexity rating based on line count.
 */
function getMockComplexity(lineCount: number): string {
  if (lineCount < 5) return 'Low';
  if (lineCount < 15) return 'Medium';
  return 'High';
}
/**
 * Generates mock performance rating (random for realism).
 */
function getMockPerformance(): string {
  const ratings = ['Excellent', 'Good', 'Average', 'Needs Optimization'];
  return ratings[Math.floor(Math.random() * ratings.length)];
}
/**
 * Generates mock readability score (random for realism).
 */
function getMockReadability(): string {
  const scores = ['Excellent', 'Good', 'Fair', 'Could Be Improved'];
  return scores[Math.floor(Math.random() * scores.length)];
}
/**
 * Generates mock test coverage percentage (random for realism).
 */
function getMockTestCoverage(): string {
  const percentage = Math.floor(Math.random() * 100);
  return `${percentage}% (estimated)`;
}